






MAIN_FILE = main


main: $(MAIN_FILE).tex refs.bib
	pdflatex $(MAIN_FILE).tex


clean:
	$(RM) main.aux
	$(RM) main.bbl
	$(RM) main.blg
	$(RM) main.synctex.gz
	$(RM) main.log
	$(RM) main.out
	$(RM) main.pdf
	$(RM) main.toc


