




PROGRAM_BINARY              = main.exe
PROGRAM_NAME                = main.cpp
PROGRAM_MAIN_FOLDER_INCLUDE = .


main.exe: $(PROGRAM_NAME)
	g++ -std=c++11 $(PROGRAM_NAME) -I $(PROGRAM_MAIN_FOLDER_INCLUDE) -o main


clean :
	$(RM) $(PROGRAM_BINARY)




